version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "task-board-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1uehhn1ir7rjc"
s3_prefix = "task-board-api"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
